# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Locale, timezone and encoding
locale                   : "en-IE"
timezone                 : Europe/Madrid
encoding                 : "utf-8"

# Site Settings
title                    : "David Martínez Carpena"
title_separator          : "-"
name                     : &name "David Martínez Carpena"
description              : &description "I'm an adjunct lecturer at the University of Barcelona, recently graduated from a Master in advanced mathematics."
url                      : https://dvmcarpena.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "dvmcarpena/dvmcarpena.github.io"

# Reading Files
theme: null
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - assets/js/_main.js
  - assets/sources
  - assets/images/icon/sources
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - vendor
keep_files:
  - .git
  - .svn

# Collections
collections_dir: "_collections"
collections:
  talks:
    output: false
  posters:
    output: false
# permalink: /:categories/:title/
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "files"
    values:
      files: true

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all

# Sass/SCSS
# - http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-gist
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-gist
  - jemoji
