# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Locale, timezone and encoding
locale                   : "en-IE"
timezone                 : Europe/Madrid
encoding                 : "utf-8"

# Site Settings
title                    : "David Martínez Carpena"
title_separator          : "-"
name                     : &name "David Martínez Carpena"
description              : &description "I'm an adjunct lecturer at the University of Barcelona, recently graduated from a Master in advanced mathematics."
url                      : https://dvmcarpena.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "dvmcarpena/dvmcarpena.github.io"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "dvmcarpena"
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links                  : # An array of links to social media profiles

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/sources
  - assets/images/icon/sources
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn

# Collections
collections:
  talks:
    output: false
# permalink: /:categories/:title/
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "files"
    values:
      files: true

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-gist
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-gist
  - jemoji
